### ISSUE TITLE
"`chain`" grouping could be more clearly defined as "`network`" 

### ISSUE THREAD

**Issue by chrishobcroft** [utxo-foundation/prague-blockchain-week#5]
Describing Arbitrum or Optimism as a `chain` feels weird, but it feels like they both should belong in that list.

If the list was called `network` instead, then it would fit more appropriately.

**Comment by burningtree** [comment]
I see no problem with naming Optimism as a chain. After all, it's a blockchain and chain is just an abbreviation of the word blockchain, isn't it?

<img width="579" alt="Screenshot 2023-03-22 at 18 39 04" src="https://user-images.githubusercontent.com/67269/226991257-fa26c3e0-7c5e-49a0-a381-2d55992bce77.png">

BTW We really don't need any records like Arbitrum or Optimism in the DB unless an some event directly targets them (Optimism Event, L2 event..).
