### ISSUE TITLE
I was send here from telegram

### ISSUE THREAD

**Issue by 113kw** [utxo-foundation/prague-blockchain-week#8]
Hello I would love to be able to learn to work with this and to add more events. We have Blockchain week events planned in Prague 7 location, how can I add them, I was asking in telegram, I filled the form, I was googling how to work with it here, but I cant figure out how to add events, thx for any asssistance

**Comment by burningtree** [comment]
Ahoj!

You can either add events yourself by adding the files and doing a Pull Request, there are plenty of tutorials on the internet on how to do this:

- https://opensource.com/article/19/7/create-pull-request-github
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Or, if that is too difficult, then this form can be used to add it:
- https://prgblockweek.com/submit-event

In any case, you can open an Issue like this and say exactly what you want to change or add :)
